title: Jacques Diambra-Odi # your name (or website title) here
logo: "/headshot (2).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist 
  <br><br>
  Self-motivated, curious, diligent, and goal-oriented Data Scientist eager to apply my Python skills to solve business problems. With a background in science, I bring +8 years of analytical thinking, data analysis, attention to detail and problem solving to the table.  
  <br><br>
  <a href="https://www.linkedin.com/in/jacques-diambra-odi-6496ba24/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-69MVL0BC84 # your Google Analytics tracking ID here
