title: Jacques Diambra-Odi # your name (or website title) here
logo: "Images/headshot 6.jpg?raw=true" # your photo (or logo) here
description:
  # your text below (remove <br> elements if you don't need line breaks)
  <strong>Data Scientist</strong>
  <br><br>

  <br><br>
  <a href="https://www.linkedin.com/in/jodiambra/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
# google_analytics: G-69MVL0BC84 # your Google Analytics tracking ID here
